<?php
define("trangchu","主頁");
define("gioithieu","介紹");
define("tintuc","新聞");
define("lienhe","聯繫");
define("motasanpham","描述");
define("sanpham","產品");
define("luotxem","视图");
define("masp","产品代码");
define("ngaydang","提交日期");
define("tintuckhac","其他新闻");
define("hotrotructuyen","Support Online");
define("dangonline","Online");
define("tongtruycap","Total");
define("diachi","地址");
define("dangkynhantinthanhcong","註冊成功接收新聞，我們會盡快與您聯繫");
define("sodienthoai","电话号码");
define("hovaten","名字和姓氏");
define("chude","主题");
define("noidung","内容");
define("matkhaumoi","New password");
define("nhaplaimatkhaumoi","Re-new password");
define("gui","发送");
define("nhaplai","重新输入");
define("dangky","Sign Up");
define("khongtimthayketqua","没有找到任何结果");
define("timduongdi","Find a way");
define("dinhkemtaptin","Attachment file");
define("mabaomat","Security code");
define("dichvu","Service");
define("timkiem","搜索");
define("capnhat","更新资料");
define("boqua","跳跃");
define("phuongxa","Wards");
define("truycapngay","Today");
define("dangkynhantin","報名參加");
define("quanhuyen","区");
define("vuilongchonquanhuyen","请选择一个地区");
define("soluongqualon","Quantity is not greater than 999");
define("hoten","Full name");
define("chitietsanpham","产品详情");
define("xemthem","查看更多");
define("tuyendung","Recruitment");
define("gia","价钱");
define("thongtincanhan","Information personal");
define("thuvienanh","Album");
define("sanphamnoibat","Featured products");
define("ketquatimkiem","搜索结果");
define("dathang","Add to cart");
define("matkhaucu","Old password");
define("giohang","大车");
define("hinh","数字");
define("soluong","量");
define("thanhtien","变成钱");
define("tinhthanh","省/市");
define("nhaptukhoatimkiem","输入搜索关键字...");
define("tinhtrang","Status");
define("hethang","Out of stock");
define("dangcapnhat","更新中");
define("danhmucsanpham","產品介紹");
define("trongtuan","Week");
define("thaydoimatkhau","Change password");
define("thongketruycap","Statistical access");
define("thongtinsanpham","產品信息");
define("vuilongchonphuongxa","请选择病房");
define("traloi","Answer");
define("huy","取消");
define("binhluanve","comments about");
define("moibanthaoluan","Please discuss. Please enter Vietnamese accented, minimum 10 characters.");
define("co","Have");
define("danhgia","Review");
define("xacnhan","确认");
define("sanphamcungloai","同类产品");
define("conhang","Stocking");
define("thanhtoan","工资");
define("chonvideo","Choose video");
define("slogandangkynhantin","输入您的信息以接收我们的最新信息");
define("giamoi","新的价格");
define("giacu","旧价格");
define("binhluan","評論");
define("baivietkhac","其他文章");
define("banmuonxoasanphamnay","您要从购物车中删除此产品吗？");
define("soluongkhongnhohonkhong","Order quantity must not be less than 0");
define("muatiep","买多点");
define("xoatatca","删除所有");
define("kichthuoc","Size");
define("dangnhap","Login");
define("taikhoan","Username");
define("matkhau","Password");
define("nhomatkhau","Remember password");
define("quenmatkhau","Forget password");
define("nhaplaimatkhau","Confirm password");
define("dienthoai","Phone");
define("banchuacotaikhoan","You don't have a account");
define("laymatkhau","Get password");
define("apdung","Apply");
define("phivanchuyen","运输费");
define("tamtinh","临时");
define("tongtien","总钱");
define("map","Map");
define("donhang","订购");
define("lichsudonhang","订单历史");
define("trangdau","第一页");
define("trangcuoi","最后一页");
define("trangbantruycapkhongtontai","您访问的页面不存在。");
define("vetrangchu","在首页上");
define("chiase","分享");
define("xoa","擦除");
define("mausac","Color");
define("thongtingiaohang","物流信息");
define("phuongthucvanchuyen","Shipping method");
define("vuilongchontinhthanh","请选择一个省");
define("yeucaukhac","其他要求（可选）");
define("khongtontaisanphamtronggiohang","您的购物车中有N个商品！");
define("giohangcuaban","您的购物车");
define("vuilongchonsizevamau","Please select size and color !");
define("dangkytaiday","Sign up here");
define("nhaphoten","Enter your full name");
define("nhaptaikhoan","Enter your account");
define("nhapmatkhau","Choose password (5-15 chars)");
define("nhapemail","Enter your email address");
define("nhapdienthoai","Enter your number phone");
define("nhapdiachi","Enter your address");
define("nhapngaysinh","Enter your birthday");
define("gioitinh","Gender");
define("nam","Male");
define("nu","Female");
define("kichhoat","Active");
define("nhapmakichhoat","Enter your active code");
define("nhapmatkhaucu","Enter old password");
define("nhapmatkhaumoi","Enter new password");
define("thich","Like");
define("dathich","Liked");
define("taithembinhluan","Get more comments");
define("trangke","下一页");
define("trangtruoc","上一页");
define("hinhanh","图片");
define("tensanpham","产品名称");
define("duong","Street");
define("hinhthucthanhtoan","付款方式");
define("vuilongnhaphoten","请输入您的名字和姓氏");
define("vuilongnhapsodienthoai","请输入电话号码");
define("vuilongnhapdiachi","请输入您的地址");
define("vuilongnhapdiachiemail","请输入您的电子邮件地址");
define("vuilongnhapchude","请输入主题");
define("vuilongnhapnoidung","请输入内容");
define("chon","选择");
define("tieptucmuahang","继续购买");
define("trongthang","Month");
define("chinhsachkhachhang","銷售政策");
define("thuonghieu","Brand");
define("vuilongnhaptaikhoan","Please enter an account");
define("vuilongnhapmatkhau","Please enter a password");
define("vuilongnhaplaimatkhau","Please enter the password again");
define("vuilongnhapngaysinh","Please enter your birthday");
define("ngaysinh","Date of birth");
define("vuilongnhapmakichhoat","Please enter the activation code");
define("dangxuat","Logout");
define("homnay","Today");
define("homqua","Yesterday");
define("thongbao","通知");
define("thoat","出口");
define("chuanhaptukhoatimkiem","尚未输入搜索关键字");
define("capnhatthongtin","更新信息");
define("noidungdangcapnhat","内容正在更新");
define("banggia","價目單價目表");
define("dondat","訂單");
define("sanphamdaxem","瀏覽過的產品");
define("hotlinehotro","热线客户支持");
define("nhaphoten","输入您的全名");
define("nhapdienthoai","输入电话");
define("nhapemail","输入你的电子邮箱");
define("nhapdiachi","输入地址");
define("nhapnoidung","导入内容");
define("chinhsach","政策");
define("thongtinlienhe","聯繫信息");
define("taisaochon","為什麼選擇我們");
define("tintucsukien","活動新聞");
define("catalogue","目錄");
define("sanphamkhuyenmai","促銷產品");
define("themvaogiohang","添加到購物車");
define("email","电子邮件");
define("dangkynhantinthatbai","註冊接收新聞失敗。 請稍後再試。");
define("guilienhethanhcong","聯繫人已成功發送");
define("guilienhethatbai","聯繫失敗。 請稍後再試");
define("guilienhethatbai","聯繫失敗。 請稍後再試");
define("dathangthanhcong","訂單信息已成功發送");
?>